//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindTouch.RoslynAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindTouch.RoslynAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cases of enum should be covered in switch statement.
        /// </summary>
        internal static string MindTouchEnumSwitchAnalyzerDescription {
            get {
                return ResourceManager.GetString("MindTouchEnumSwitchAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch on enum &apos;{0}&apos; is missing the following members: &apos;{1}&apos;.
        /// </summary>
        internal static string MindTouchEnumSwitchAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MindTouchEnumSwitchAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at all cases of enum covered in switch statement.
        /// </summary>
        internal static string MindTouchEnumSwitchAnalyzerTitle {
            get {
                return ResourceManager.GetString("MindTouchEnumSwitchAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections that are passed as parameters or returned from functions should be materialized.
        /// </summary>
        internal static string MindTouchMaterializedEnumerableAnalyzerDescription {
            get {
                return ResourceManager.GetString("MindTouchMaterializedEnumerableAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection may or may not be materialized.
        /// </summary>
        internal static string MindTouchMaterializedEnumerableAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MindTouchMaterializedEnumerableAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmaterialized collection.
        /// </summary>
        internal static string MindTouchMaterializedEnumerableAnalyzerTitle {
            get {
                return ResourceManager.GetString("MindTouchMaterializedEnumerableAnalyzerTitle", resourceCulture);
            }
        }
    }
}
